// Generated by Wrangler on Tue Jun 18 2024 12:18:15 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  KVDATA: KVNamespace;
  R2STORAGE: R2Bucket;
  D1DATA: D1Database;
}
