// Generated by Wrangler on Fri Jun 28 2024 16:57:45 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  KVDATA: KVNamespace;
  D1DATA: D1Database;
}
