#:schema node_modules/wrangler/config-schema.json
name = "tombaker-blog"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "/.vercel/output/static"

# Enter your account id
# This can be found at https://dash.cloudflare.com/ --> Workers & Pages
#  --> Overview, then in the right sidebar
account_id = "b5b0579b44a73e60f8dc0d570dbc523d"

# Run the `wrangler kv:namespace create sonicjs` command and copy the id below
# Run the `wrangler kv:namespace create sonicjs --preview` command and copy the preview_id below
# Only update the preview_id and id, leave the binding name as "KVDATA"
kv_namespaces = [
  { binding = "KVDATA", preview_id = "43937d09383e484ea88967f4c7377124", id = "eb3eaaf368f6478589a9d84ad380d1ba" },
]

# Run the `wrangler d1 create sonicjs` command and copy the id below
[[d1_databases]]
binding = "D1DATA"
database_name = "sonicjs"
database_id = "9043b293-b8b3-4a6f-ad24-0fc39e093816"

# Using Cloudflare R2 (similar to AWS S3) is only necessary if you plan to use SonicJs to manage file assets
# Run the `wrangler r2 bucket create sonicjs` command and uncomment the section below
[[r2_buckets]]
binding = 'R2STORAGE'
bucket_name = 'sonicjs'

[env.development]
vars = { ENVIRONMENT = "development" }
